### ISSUE TITLE
Issue with account creation 

### ISSUE THREAD

**Issue by cking826** [oss-slu/Seeing-is-Believing#24]
Some users are not receiving the confirmation email that should be generated upon registering for a new account, and thus, are not able to login to the site. I'm wondering if this may be an issue with email extensions that are not just '@university.edu' since it has been reported for one that was '@email.university.edu'.

**Comment by HalimaMalik** [comment]
Users now receive verification emails upon creation of a new account. If the emails are unverified they cannot login to the app
