### ISSUE TITLE
Creation of Developer database

### ISSUE THREAD

**Issue by HalimaMalik** [oss-slu/Seeing-is-Believing#51]
Currently, all testing information goes directly to the live database. We need to make a copy of the database that is different from the live database so that there is no testing/redundant data in the live environment.

**Comment by kate-holdener** [comment]
In the src/config.js file, we have a firebase section. The values in this section need to be replaced with environment variables.

A dev firebase instance for this project needs to be created. To run the application in the development in testing, the environment variables in the src/config.js should point to the dev version of the firebase instance.

**Comment by LikhitaPulijala** [comment]
This task will be divided into parts:
1. By viewing the latest  structure of the production database, create a duplicate db to use it for testing.
2. Next create environment variables for dev database

**Comment by kate-holdener** [comment]
I wonder if it would be better to use a Firebase Datastore emulator for testing: https://cloud.google.com/datastore/docs/tools/datastore-emulator
